version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: calendar_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-calendar_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-calendar_pass}
      POSTGRES_DB: ${POSTGRES_DB:-calendar_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-calendar_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: calendar_postgres_data