services:
  - type: web
    name: calendar-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        sync: false  # Will be set manually in Render dashboard
    healthCheckPath: /