#!/bin/bash

echo "🚀 Running database migration on Render production environment"
echo ""
echo "This script will help you run the recurrence migration on production."
echo ""

# Step 1: Connect to Render service
echo "Step 1: Connecting to your Render service..."
echo "Running: render ssh --service calendar-app"
echo ""
echo "Please run the following commands manually:"
echo ""
echo "1. First, connect to your Render service:"
echo "   $ render ssh --service calendar-app"
echo ""
echo "2. Once connected, run the migration:"
echo "   $ python migrate_recurrence.py"
echo ""
echo "3. You should see:"
echo "   Added recurrence_type column"
echo "   Added recurrence_group_id column and index"
echo "   Migration completed successfully!"
echo ""
echo "4. Exit the shell:"
echo "   $ exit"
echo ""
echo "Alternative: Use Render Dashboard"
echo "1. Go to https://dashboard.render.com"
echo "2. Click on your 'calendar-app' service"
echo "3. Click 'Shell' tab"
echo "4. Run: python migrate_recurrence.py"