#!/bin/bash

echo "🔍 Deployment Verification Steps:"
echo ""
echo "1. Check deployment status:"
echo "   render deploys list calendar-app"
echo ""
echo "2. Check if latest commit is deployed:"
echo "   - Latest commit should be: 'Add event recurrence functionality'"
echo "   - Check in Render Dashboard under 'Events' tab"
echo ""
echo "3. Force a manual deploy if needed:"
echo "   - Go to Render Dashboard"
echo "   - Click 'Manual Deploy' → 'Deploy latest commit'"
echo ""
echo "4. Check service logs for errors:"
echo "   render logs calendar-app --tail 50"
echo ""
echo "5. Common issues to look for:"
echo "   - ModuleNotFoundError: No module named 'dateutil'"
echo "   - 400 Bad Request errors"
echo "   - Database connection errors"